# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: DownloadBuildArtifacts@0
  displayName: 'Download artifacts'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    downloadPath: 'releases_drop'

- task: GooglePlayRelease@4
  inputs:
    serviceConnection: 'GooglePlayConnectionService'
    applicationId: 'com.application.azuredemo'
    action: 'SingleBundle'
    bundleFile: 'drop/app/build/outputs/bundle/release/*.aab'
    track: 'internal'