# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'bundleRelease'

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.aab'
    jarsign: true
    jarsignerKeystoreFile: 'keystore.jks'
    jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
    jarsignerKeystoreAlias: 'upload'
    jarsignerKeyPassword: '$(jarsignerKeyPassword)'
    zipalign: true

- task: CopyFiles@2
  inputs:
    contents: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- task: DownloadBuildArtifacts@0
  displayName: 'Download artifacts'
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    downloadPath: 'releases_drop'

- task: GooglePlayRelease@4
  inputs:
    serviceConnection: 'GooglePlayConnectionService'
    applicationId: 'com.application.azuredemo'
    action: 'SingleBundle'
    bundleFile: 'releases_drop/android_packages/*.aab'
    track: 'internal'